steps:
- name: 'docker/compose'
  id: 'Build anyway db and backend docker images'
  entrypoint: 'sh'
  args: ['-c', 'docker-compose build --force-rm --no-cache --build-arg ANYWAY_BACKEND_IMG=$PROJECT_ID:$COMMIT_SHA --build-arg ANYWAY_BACKEND_DB_IMG=$PROJECT_ID-db:$COMMIT_SHA --build-arg DATABASE_URL=$$DATABASE_URL --build-arg POSTGRES_PASSWORD=$$POSTGRES_PASSWORD --build-arg POSTGRES_USER=$$POSTGRES_USER --build-arg POSTGRES_DB=$$POSTGRES_DB']
  secretEnv: ['DATABASE_URL', 'POSTGRES_PASSWORD', 'POSTGRES_USER', 'POSTGRES_DB']
  env:
  - 'ANYWAY_BACKEND_IMG=$PROJECT_ID:$COMMIT_SHA'
  - 'ANYWAY_BACKEND_DB_IMG=$PROJECT_ID-db:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Tag backend docker image'
  args: ['tag', '$PROJECT_ID:$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$PROJECT_ID:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Tag db docker image'
  args: ['tag', '$PROJECT_ID-db:$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$PROJECT_ID-db:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id:   'Push backend image into cloud repository'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/$PROJECT_ID:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  id:   'Push db image into cloud repository'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/$PROJECT_ID-db:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gke-deploy'
  id:   'Deploy db image into k8s cluster'
  args:
  - run
  - --output=./output-anyway-db
  - --filename=./anyway-db-k8s.yml
  - --image=eu.gcr.io/$PROJECT_ID/$PROJECT_ID-db:$COMMIT_SHA
  - --location=europe-west3-a
  - --cluster=anyway-dev-cluster-1
  - en
 
- name: 'gcr.io/cloud-builders/gke-deploy'
  id:   'Deploy backend image into k8s cluster'
  args:
  - run
  - --output=./output-anyway-backend
  - --filename=./anyway-backend-k8s.yml
  - --image=eu.gcr.io/$PROJECT_ID/$PROJECT_ID:$COMMIT_SHA
  - --location=europe-west3-a
  - --cluster=anyway-dev-cluster-1
  - en

- name: 'gcr.io/cloud-builders/kubectl'
  id:   'Run db migration'
  entrypoint: 'bash'
  args: ['-c', 'chmod +x ./db-migration.sh && ./db-migration.sh']
  env:
  - CLOUDSDK_COMPUTE_ZONE=europe-west3-a
  - CLOUDSDK_CONTAINER_CLUSTER=anyway-dev-cluster-1

# encrypted values
secrets:
 - kmsKeyName: projects/anyway-backend/locations/europe-west3/keyRings/anyway-keyring/cryptoKeys/ANYWAY-KEY
   secretEnv:
      DATABASE_URL: CiQAdQc2s3GSGOUhS65gO4ZyG0NNc507R4Pb+/eFin88OCDeRxsSeQBVstM2QIvW/RKUgLF7ojy2HjBYKcVsSYtc3syMSxFtO3esMHbGKbSd6arltiey7N7eU2tIiFJoZzxeed06Aa5xoz5WA/1/hcBGropwg2ytkY5IeXoj/qSbCShQe+HSQZf+3uYW4E2WR5zT2kRKxWAKHptnysgzJF0=
      POSTGRES_PASSWORD: CiQAdQc2s0A1OjCowD/tzNrSx4qA7yMvToXIMcGQGmav6RIrVPISNwBVstM2cFf/XMwyUZ6NvyOanMHaxFRshxT9OziOr4mV8ppQCUcwTRdrG/noQTHvMb8Taj5eQlM=
      POSTGRES_USER: CiQAdQc2szzdQlVwKWtVJvKOHMGoF79S86ikJmSMTHfE91xo0O8SNgBVstM2yTgaL25muc4QSZ45cews5Ku8dpIae2y7cImB9cpVq8qYOr6uJTsDJ1FTkiOCpSfaNA==
      POSTGRES_DB: CiQAdQc2s4kpmARxkpjw9JKs+gJ5NIWQDoxyOfe4NtDlpVJnXeESMgBVstM2HKmA+c97TP/ncIBBgYY0dCzJmTsPCt6JbHEOuC0zx1WAE/8NooLXIbs9B/Wq

    
  