"""Add Waze Tables

Revision ID: 317d8e218c36
Revises: ab9834c903dd
Create Date: 2020-03-24 22:36:27.622450

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '317d8e218c36'
down_revision = 'ab9834c903dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waze_alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lontitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('magvar', sa.Integer(), nullable=True),
    sa.Column('number_thumbs_up', sa.Integer(), nullable=True),
    sa.Column('report_rating', sa.Integer(), nullable=True),
    sa.Column('reliability', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Text(), nullable=True),
    sa.Column('alert_subtype', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('road_type', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='waze'
    )
    op.create_index(op.f('ix_waze_waze_alerts_created_at'), 'waze_alerts', ['created_at'], unique=False, schema='waze')
    op.create_index('ix_waze_waze_alerts_geom', 'waze_alerts', ['geom'], unique=False, schema='waze', postgresql_using='gist')
    op.create_table('waze_traffic_jams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('line', sa.Text(), nullable=True),
    sa.Column('speed_kmh', sa.Integer(), nullable=True),
    sa.Column('turn_type', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('segments', sa.Text(), nullable=True),
    sa.Column('road_type', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('end_node', sa.Text(), nullable=True),
    sa.Column('blocking_alert_uuid', sa.Text(), nullable=True),
    sa.Column('start_node', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, spatial_index=False), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='waze'
    )
    op.create_index(op.f('ix_waze_waze_traffic_jams_created_at'), 'waze_traffic_jams', ['created_at'], unique=False, schema='waze')
    op.create_index('ix_waze_waze_traffic_jams_geom', 'waze_traffic_jams', ['geom'], unique=False, schema='waze', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waze_waze_traffic_jams_geom', table_name='waze_traffic_jams', schema='waze')
    op.drop_index(op.f('ix_waze_waze_traffic_jams_created_at'), table_name='waze_traffic_jams', schema='waze')
    op.drop_table('waze_traffic_jams', schema='waze')
    op.drop_index('ix_waze_waze_alerts_geom', table_name='waze_alerts', schema='waze')
    op.drop_index(op.f('ix_waze_waze_alerts_created_at'), table_name='waze_alerts', schema='waze')
    op.drop_table('waze_alerts', schema='waze')
    # ### end Alembic commands ###
